name: Link Checker

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
  pull_request:
    paths:
      - '**.md'
      - '**.mdc'

permissions:
  contents: read
  issues: write

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress '**/*.md' '**/*.mdc'
          fail: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Issue on Failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Broken Links Detected
          content-filepath: ./lychee/out.md
          labels: bug, documentation

